[package]
name = "file_inspector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.73"
assert_approx_eq = "1.1.0"
terminal_size = "0.2.6"
thiserror = "1.0.45"
